import type { Metadata } from "next";
import { Rubik  } from "next/font/google";
import "./globals.css";
import Env from "@/utils/env";
import {ClerkProvider} from "@clerk/nextjs";
import { CookiesProvider } from 'next-client-cookies/server';

const rubik = Rubik ({
    weight: '400',
    subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Urbex Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  Env.configureEnvironment();

  return (
      <CookiesProvider>
          <ClerkProvider>
            <html lang="en">
              <body className={rubik.className}>{children}</body>
            </html>
          </ClerkProvider>
      </CookiesProvider>
  );
}
